### ISSUE TITLE
feature: track unix timestamp height

### ISSUE THREAD

**Issue by 0xBasically** [yearn/ymonitor#3]
Lets track unix timestamp height on v1 api (like we track block height) for v1 apy like we track blockheight for archive nodes. 

timestamp field should all be the same for all vaults output

"updated:1687367714"

urls: https://api.yearn.finance/v1/chains/1/vaults/all (for all networks)

We want to know if the s3 scripts (that output to v1 api stop updating) and be able to visualize this in grafana.

**Comment by crebsy** [comment]
completed by #4
